#nullable enable

namespace Rv3dViewer.HighQualityRenderPlugin;

partial class RenderPipelineSettingsControl
{
    private System.ComponentModel.IContainer? components;
    private TableLayoutPanel pipelineLayoutPanel = null!;
    private GroupBox presetGroupBox = null!;
    private FlowLayoutPanel presetFlowLayoutPanel = null!;
    private RadioButton fastRadioButton = null!;
    private RadioButton balancedRadioButton = null!;
    private RadioButton highQualityRadioButton = null!;
    private Label renderScaleLabel = null!;
    private NumericUpDown renderScaleNumericUpDown = null!;
    private Label executionModeLabel = null!;
    private ComboBox executionModeComboBox = null!;
    private Label denoiserLabel = null!;
    private ComboBox denoiserComboBox = null!;
    private CheckBox adaptiveSamplingCheckBox = null!;
    private CheckBox hdriImportanceCheckBox = null!;
    private Label glassQualityLabel = null!;
    private ComboBox glassQualityComboBox = null!;
    private Label textureQualityLabel = null!;
    private ComboBox textureQualityComboBox = null!;
    private Label fireflyClampLabel = null!;
    private NumericUpDown fireflyClampNumericUpDown = null!;
    private CheckBox exportAovCheckBox = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        pipelineLayoutPanel = new TableLayoutPanel();
        presetGroupBox = new GroupBox();
        presetFlowLayoutPanel = new FlowLayoutPanel();
        fastRadioButton = new RadioButton();
        balancedRadioButton = new RadioButton();
        highQualityRadioButton = new RadioButton();
        renderScaleLabel = new Label();
        renderScaleNumericUpDown = new NumericUpDown();
        executionModeLabel = new Label();
        executionModeComboBox = new ComboBox();
        denoiserLabel = new Label();
        denoiserComboBox = new ComboBox();
        adaptiveSamplingCheckBox = new CheckBox();
        hdriImportanceCheckBox = new CheckBox();
        glassQualityLabel = new Label();
        glassQualityComboBox = new ComboBox();
        textureQualityLabel = new Label();
        textureQualityComboBox = new ComboBox();
        fireflyClampLabel = new Label();
        fireflyClampNumericUpDown = new NumericUpDown();
        exportAovCheckBox = new CheckBox();
        pipelineLayoutPanel.SuspendLayout();
        presetGroupBox.SuspendLayout();
        presetFlowLayoutPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)renderScaleNumericUpDown).BeginInit();
        ((System.ComponentModel.ISupportInitialize)fireflyClampNumericUpDown).BeginInit();
        SuspendLayout();
        pipelineLayoutPanel.AutoScroll = true;
        pipelineLayoutPanel.ColumnCount = 2;
        pipelineLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 46F));
        pipelineLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 54F));
        pipelineLayoutPanel.Controls.Add(presetGroupBox, 0, 0);
        pipelineLayoutPanel.SetColumnSpan(presetGroupBox, 2);
        pipelineLayoutPanel.Controls.Add(renderScaleLabel, 0, 1);
        pipelineLayoutPanel.Controls.Add(renderScaleNumericUpDown, 1, 1);
        pipelineLayoutPanel.Controls.Add(executionModeLabel, 0, 2);
        pipelineLayoutPanel.Controls.Add(executionModeComboBox, 1, 2);
        pipelineLayoutPanel.Controls.Add(denoiserLabel, 0, 3);
        pipelineLayoutPanel.Controls.Add(denoiserComboBox, 1, 3);
        pipelineLayoutPanel.Controls.Add(adaptiveSamplingCheckBox, 0, 4);
        pipelineLayoutPanel.SetColumnSpan(adaptiveSamplingCheckBox, 2);
        pipelineLayoutPanel.Controls.Add(hdriImportanceCheckBox, 0, 5);
        pipelineLayoutPanel.SetColumnSpan(hdriImportanceCheckBox, 2);
        pipelineLayoutPanel.Controls.Add(glassQualityLabel, 0, 6);
        pipelineLayoutPanel.Controls.Add(glassQualityComboBox, 1, 6);
        pipelineLayoutPanel.Controls.Add(textureQualityLabel, 0, 7);
        pipelineLayoutPanel.Controls.Add(textureQualityComboBox, 1, 7);
        pipelineLayoutPanel.Controls.Add(fireflyClampLabel, 0, 8);
        pipelineLayoutPanel.Controls.Add(fireflyClampNumericUpDown, 1, 8);
        pipelineLayoutPanel.Controls.Add(exportAovCheckBox, 0, 9);
        pipelineLayoutPanel.SetColumnSpan(exportAovCheckBox, 2);
        pipelineLayoutPanel.Dock = DockStyle.Fill;
        pipelineLayoutPanel.Name = "pipelineLayoutPanel";
        pipelineLayoutPanel.Padding = new Padding(6);
        pipelineLayoutPanel.RowCount = 10;
        pipelineLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 76F));
        for (var row = 1; row < 10; row++) pipelineLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        presetGroupBox.Controls.Add(presetFlowLayoutPanel);
        presetGroupBox.Dock = DockStyle.Fill;
        presetGroupBox.Name = "presetGroupBox";
        presetGroupBox.Text = "品質預設";
        presetFlowLayoutPanel.Controls.Add(fastRadioButton);
        presetFlowLayoutPanel.Controls.Add(balancedRadioButton);
        presetFlowLayoutPanel.Controls.Add(highQualityRadioButton);
        presetFlowLayoutPanel.Dock = DockStyle.Fill;
        presetFlowLayoutPanel.Name = "presetFlowLayoutPanel";
        presetFlowLayoutPanel.Padding = new Padding(0, 4, 0, 0);
        presetFlowLayoutPanel.WrapContents = false;
        fastRadioButton.AutoSize = true;
        fastRadioButton.Name = "fastRadioButton";
        fastRadioButton.Text = "快速";
        fastRadioButton.CheckedChanged += PresetRadioButton_CheckedChanged;
        balancedRadioButton.AutoSize = true;
        balancedRadioButton.Name = "balancedRadioButton";
        balancedRadioButton.Text = "平衡";
        balancedRadioButton.CheckedChanged += PresetRadioButton_CheckedChanged;
        highQualityRadioButton.AutoSize = true;
        highQualityRadioButton.Name = "highQualityRadioButton";
        highQualityRadioButton.Text = "高品質";
        highQualityRadioButton.CheckedChanged += PresetRadioButton_CheckedChanged;
        renderScaleLabel.Dock = DockStyle.Fill;
        renderScaleLabel.Text = "Render Scale（%）";
        renderScaleLabel.TextAlign = ContentAlignment.MiddleLeft;
        renderScaleNumericUpDown.Dock = DockStyle.Fill;
        renderScaleNumericUpDown.Minimum = 25M;
        renderScaleNumericUpDown.Maximum = 100M;
        renderScaleNumericUpDown.Increment = 5M;
        renderScaleNumericUpDown.Value = 100M;
        renderScaleNumericUpDown.ValueChanged += PipelineSetting_Changed;
        executionModeLabel.Dock = DockStyle.Fill;
        executionModeLabel.Text = "運算裝置";
        executionModeLabel.TextAlign = ContentAlignment.MiddleLeft;
        executionModeComboBox.Dock = DockStyle.Fill;
        executionModeComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
        executionModeComboBox.Items.AddRange(new object[] { "自動", "GPU", "CPU" });
        executionModeComboBox.SelectedIndex = 0;
        executionModeComboBox.SelectedIndexChanged += PipelineSetting_Changed;
        denoiserLabel.Dock = DockStyle.Fill;
        denoiserLabel.Text = "Denoiser";
        denoiserLabel.TextAlign = ContentAlignment.MiddleLeft;
        denoiserComboBox.Dock = DockStyle.Fill;
        denoiserComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
        denoiserComboBox.Items.AddRange(new object[] { "關閉", "內建 AOV", "OIDN" });
        denoiserComboBox.SelectedIndex = 2;
        denoiserComboBox.SelectedIndexChanged += PipelineSetting_Changed;
        adaptiveSamplingCheckBox.AutoSize = true;
        adaptiveSamplingCheckBox.Checked = true;
        adaptiveSamplingCheckBox.Text = "Adaptive Sampling";
        adaptiveSamplingCheckBox.CheckedChanged += PipelineSetting_Changed;
        hdriImportanceCheckBox.AutoSize = true;
        hdriImportanceCheckBox.Checked = true;
        hdriImportanceCheckBox.Text = "HDRI Importance Sampling";
        hdriImportanceCheckBox.CheckedChanged += PipelineSetting_Changed;
        glassQualityLabel.Dock = DockStyle.Fill;
        glassQualityLabel.Text = "玻璃品質";
        glassQualityLabel.TextAlign = ContentAlignment.MiddleLeft;
        glassQualityComboBox.Dock = DockStyle.Fill;
        glassQualityComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
        glassQualityComboBox.Items.AddRange(new object[] { "快速", "物理正確" });
        glassQualityComboBox.SelectedIndex = 1;
        glassQualityComboBox.SelectedIndexChanged += PipelineSetting_Changed;
        textureQualityLabel.Dock = DockStyle.Fill;
        textureQualityLabel.Text = "貼圖品質";
        textureQualityLabel.TextAlign = ContentAlignment.MiddleLeft;
        textureQualityComboBox.Dock = DockStyle.Fill;
        textureQualityComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
        textureQualityComboBox.Items.AddRange(new object[] { "低（512）", "中（1024）", "原始" });
        textureQualityComboBox.SelectedIndex = 2;
        textureQualityComboBox.SelectedIndexChanged += PipelineSetting_Changed;
        fireflyClampLabel.Dock = DockStyle.Fill;
        fireflyClampLabel.Text = "Firefly Clamp";
        fireflyClampLabel.TextAlign = ContentAlignment.MiddleLeft;
        fireflyClampNumericUpDown.DecimalPlaces = 1;
        fireflyClampNumericUpDown.Dock = DockStyle.Fill;
        fireflyClampNumericUpDown.Minimum = 1M;
        fireflyClampNumericUpDown.Maximum = 100M;
        fireflyClampNumericUpDown.Value = 12M;
        fireflyClampNumericUpDown.ValueChanged += PipelineSetting_Changed;
        exportAovCheckBox.AutoSize = true;
        exportAovCheckBox.Text = "輸出 AOV／Debug 檔案";
        exportAovCheckBox.CheckedChanged += PipelineSetting_Changed;
        Controls.Add(pipelineLayoutPanel);
        Name = "RenderPipelineSettingsControl";
        Size = new Size(350, 330);
        pipelineLayoutPanel.ResumeLayout(false);
        pipelineLayoutPanel.PerformLayout();
        presetGroupBox.ResumeLayout(false);
        presetFlowLayoutPanel.ResumeLayout(false);
        presetFlowLayoutPanel.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)renderScaleNumericUpDown).EndInit();
        ((System.ComponentModel.ISupportInitialize)fireflyClampNumericUpDown).EndInit();
        ResumeLayout(false);
    }
}
