#nullable enable

namespace Rv3dViewer.RVInteriorDesignPlugin;

partial class AssetCategoryControl
{
    private System.ComponentModel.IContainer? components;
    private TableLayoutPanel filterTableLayoutPanel = null!;
    private TextBox searchTextBox = null!;
    private ComboBox sourceComboBox = null!;
    private CheckBox favoritesCheckBox = null!;
    private SplitContainer placementSplitContainer = null!;
    private ListView assetListView = null!;
    private ColumnHeader previewColumnHeader = null!;
    private ColumnHeader nameColumnHeader = null!;
    private ColumnHeader subcategoryColumnHeader = null!;
    private ColumnHeader sourceColumnHeader = null!;
    private ColumnHeader dimensionsColumnHeader = null!;
    private ColumnHeader qualityColumnHeader = null!;
    private ImageList assetThumbnailImageList = null!;
    private Panel detailPanel = null!;
    private SplitContainer previewSettingsSplitContainer = null!;
    private TableLayoutPanel detailTableLayoutPanel = null!;
    private TableLayoutPanel settingsTableLayoutPanel = null!;
    private TableLayoutPanel buttonTableLayoutPanel = null!;
    private TableLayoutPanel previewHostTableLayoutPanel = null!;
    private TableLayoutPanel previewButtonTableLayoutPanel = null!;
    private Label resultCountLabel = null!;
    private Label detailLabel = null!;
    private Label qualityLabel = null!;
    private InteriorViewportControl assetPreviewViewport = null!;
    private Button framePreviewButton = null!;
    private Button pbrPreviewButton = null!;
    private PropertyGrid placementSettingsPropertyGrid = null!;
    private Button editAssetButton = null!;
    private Button deleteAssetButton = null!;
    private Button placeButton = null!;
    private ToolTip assetToolTip = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            PrepareForDispose();
            components?.Dispose();
        }
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        filterTableLayoutPanel = new TableLayoutPanel();
        searchTextBox = new TextBox();
        sourceComboBox = new ComboBox();
        favoritesCheckBox = new CheckBox();
        placementSplitContainer = new SplitContainer();
        assetListView = new ListView();
        previewColumnHeader = new ColumnHeader();
        nameColumnHeader = new ColumnHeader();
        subcategoryColumnHeader = new ColumnHeader();
        sourceColumnHeader = new ColumnHeader();
        dimensionsColumnHeader = new ColumnHeader();
        qualityColumnHeader = new ColumnHeader();
        assetThumbnailImageList = new ImageList(components);
        detailPanel = new Panel();
        previewSettingsSplitContainer = new SplitContainer();
        detailTableLayoutPanel = new TableLayoutPanel();
        settingsTableLayoutPanel = new TableLayoutPanel();
        buttonTableLayoutPanel = new TableLayoutPanel();
        previewHostTableLayoutPanel = new TableLayoutPanel();
        previewButtonTableLayoutPanel = new TableLayoutPanel();
        resultCountLabel = new Label();
        detailLabel = new Label();
        qualityLabel = new Label();
        assetPreviewViewport = new InteriorViewportControl();
        framePreviewButton = new Button();
        pbrPreviewButton = new Button();
        placementSettingsPropertyGrid = new PropertyGrid();
        editAssetButton = new Button();
        deleteAssetButton = new Button();
        placeButton = new Button();
        assetToolTip = new ToolTip(components);
        filterTableLayoutPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)placementSplitContainer).BeginInit();
        placementSplitContainer.Panel1.SuspendLayout();
        placementSplitContainer.Panel2.SuspendLayout();
        placementSplitContainer.SuspendLayout();
        detailPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)previewSettingsSplitContainer).BeginInit();
        previewSettingsSplitContainer.Panel1.SuspendLayout();
        previewSettingsSplitContainer.Panel2.SuspendLayout();
        previewSettingsSplitContainer.SuspendLayout();
        detailTableLayoutPanel.SuspendLayout();
        settingsTableLayoutPanel.SuspendLayout();
        buttonTableLayoutPanel.SuspendLayout();
        previewHostTableLayoutPanel.SuspendLayout();
        previewButtonTableLayoutPanel.SuspendLayout();
        SuspendLayout();
        filterTableLayoutPanel.ColumnCount = 2;
        filterTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 58F));
        filterTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 42F));
        filterTableLayoutPanel.Controls.Add(searchTextBox, 0, 0);
        filterTableLayoutPanel.Controls.Add(sourceComboBox, 1, 0);
        filterTableLayoutPanel.Controls.Add(favoritesCheckBox, 0, 1);
        filterTableLayoutPanel.Dock = DockStyle.Top;
        filterTableLayoutPanel.Name = "filterTableLayoutPanel";
        filterTableLayoutPanel.RowCount = 2;
        filterTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        filterTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        filterTableLayoutPanel.Size = new Size(300, 64);
        filterTableLayoutPanel.TabIndex = 0;
        searchTextBox.Dock = DockStyle.Fill;
        searchTextBox.Name = "searchTextBox";
        searchTextBox.PlaceholderText = "搜尋此分類";
        searchTextBox.TabIndex = 0;
        searchTextBox.TextChanged += FilterControl_Changed;
        sourceComboBox.Dock = DockStyle.Fill;
        sourceComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
        sourceComboBox.Items.AddRange(new object[] { "全部來源", "內建", "本機", "線上" });
        sourceComboBox.Name = "sourceComboBox";
        sourceComboBox.TabIndex = 1;
        sourceComboBox.SelectedIndexChanged += FilterControl_Changed;
        favoritesCheckBox.AutoSize = true;
        favoritesCheckBox.AutoEllipsis = true;
        filterTableLayoutPanel.SetColumnSpan(favoritesCheckBox, 2);
        favoritesCheckBox.Dock = DockStyle.Fill;
        favoritesCheckBox.Name = "favoritesCheckBox";
        favoritesCheckBox.TabIndex = 2;
        favoritesCheckBox.Text = "只顯示我的最愛";
        favoritesCheckBox.UseVisualStyleBackColor = true;
        favoritesCheckBox.CheckedChanged += FilterControl_Changed;
        placementSplitContainer.Dock = DockStyle.Fill;
        placementSplitContainer.FixedPanel = FixedPanel.Panel2;
        placementSplitContainer.Name = "placementSplitContainer";
        placementSplitContainer.Orientation = Orientation.Horizontal;
        placementSplitContainer.Panel1.Controls.Add(assetListView);
        placementSplitContainer.Panel1MinSize = 80;
        placementSplitContainer.Panel2.Controls.Add(detailPanel);
        placementSplitContainer.Panel2MinSize = 390;
        placementSplitContainer.Size = new Size(300, 594);
        placementSplitContainer.SplitterDistance = 198;
        placementSplitContainer.SplitterWidth = 6;
        placementSplitContainer.TabIndex = 1;
        placementSplitContainer.SplitterMoved += PlacementSplitContainer_SplitterMoved;
        assetListView.Columns.AddRange(new[] { previewColumnHeader, nameColumnHeader, subcategoryColumnHeader,
            sourceColumnHeader, dimensionsColumnHeader, qualityColumnHeader });
        assetListView.Dock = DockStyle.Fill;
        assetListView.FullRowSelect = true;
        assetListView.GridLines = true;
        assetListView.HideSelection = false;
        assetListView.MultiSelect = false;
        assetListView.Name = "assetListView";
        assetListView.SmallImageList = assetThumbnailImageList;
        assetListView.TabIndex = 1;
        assetListView.UseCompatibleStateImageBehavior = false;
        assetListView.View = View.Details;
        assetListView.SelectedIndexChanged += AssetListView_SelectedIndexChanged;
        assetListView.DoubleClick += AssetListView_DoubleClick;
        assetListView.ItemDrag += AssetListView_ItemDrag;
        previewColumnHeader.Text = "預覽";
        previewColumnHeader.Width = 102;
        nameColumnHeader.Text = "名稱";
        nameColumnHeader.Width = 120;
        subcategoryColumnHeader.Text = "類型";
        subcategoryColumnHeader.Width = 72;
        sourceColumnHeader.Text = "來源";
        sourceColumnHeader.Width = 82;
        dimensionsColumnHeader.Text = "尺寸（寬×深×高）";
        dimensionsColumnHeader.Width = 145;
        qualityColumnHeader.Text = "品質";
        qualityColumnHeader.Width = 82;
        assetThumbnailImageList.ColorDepth = ColorDepth.Depth32Bit;
        assetThumbnailImageList.ImageSize = new Size(96, 72);
        assetThumbnailImageList.TransparentColor = Color.Transparent;
        detailPanel.Controls.Add(previewSettingsSplitContainer);
        detailPanel.Dock = DockStyle.Fill;
        detailPanel.Name = "detailPanel";
        detailPanel.Padding = new Padding(3);
        detailPanel.Size = new Size(300, 390);
        detailPanel.TabIndex = 2;
        previewSettingsSplitContainer.Dock = DockStyle.Fill;
        previewSettingsSplitContainer.Name = "previewSettingsSplitContainer";
        previewSettingsSplitContainer.Orientation = Orientation.Horizontal;
        previewSettingsSplitContainer.Panel1.Controls.Add(detailTableLayoutPanel);
        previewSettingsSplitContainer.Panel1MinSize = 120;
        previewSettingsSplitContainer.Panel2.Controls.Add(settingsTableLayoutPanel);
        previewSettingsSplitContainer.Panel2MinSize = 170;
        previewSettingsSplitContainer.Size = new Size(294, 384);
        previewSettingsSplitContainer.SplitterDistance = 190;
        previewSettingsSplitContainer.SplitterWidth = 6;
        previewSettingsSplitContainer.TabIndex = 0;
        previewSettingsSplitContainer.SplitterMoved += PreviewSettingsSplitContainer_SplitterMoved;
        detailTableLayoutPanel.ColumnCount = 1;
        detailTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        detailTableLayoutPanel.Controls.Add(resultCountLabel, 0, 0);
        detailTableLayoutPanel.Controls.Add(previewHostTableLayoutPanel, 0, 1);
        detailTableLayoutPanel.Dock = DockStyle.Fill;
        detailTableLayoutPanel.Name = "detailTableLayoutPanel";
        detailTableLayoutPanel.RowCount = 2;
        detailTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
        detailTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        detailTableLayoutPanel.TabIndex = 0;
        previewHostTableLayoutPanel.ColumnCount = 1;
        previewHostTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        previewHostTableLayoutPanel.Controls.Add(assetPreviewViewport, 0, 0);
        previewHostTableLayoutPanel.Controls.Add(previewButtonTableLayoutPanel, 0, 1);
        previewHostTableLayoutPanel.Dock = DockStyle.Fill;
        previewHostTableLayoutPanel.Name = "previewHostTableLayoutPanel";
        previewHostTableLayoutPanel.RowCount = 2;
        previewHostTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        previewHostTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F));
        previewHostTableLayoutPanel.TabIndex = 0;
        previewButtonTableLayoutPanel.ColumnCount = 2;
        previewButtonTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        previewButtonTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        previewButtonTableLayoutPanel.Controls.Add(framePreviewButton, 0, 0);
        previewButtonTableLayoutPanel.Controls.Add(pbrPreviewButton, 1, 0);
        previewButtonTableLayoutPanel.Dock = DockStyle.Fill;
        previewButtonTableLayoutPanel.Name = "previewButtonTableLayoutPanel";
        previewButtonTableLayoutPanel.RowCount = 1;
        previewButtonTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        previewButtonTableLayoutPanel.TabIndex = 0;
        settingsTableLayoutPanel.ColumnCount = 1;
        settingsTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        settingsTableLayoutPanel.Controls.Add(detailLabel, 0, 0);
        settingsTableLayoutPanel.Controls.Add(qualityLabel, 0, 1);
        settingsTableLayoutPanel.Controls.Add(placementSettingsPropertyGrid, 0, 2);
        settingsTableLayoutPanel.Controls.Add(buttonTableLayoutPanel, 0, 3);
        settingsTableLayoutPanel.Dock = DockStyle.Fill;
        settingsTableLayoutPanel.Name = "settingsTableLayoutPanel";
        settingsTableLayoutPanel.RowCount = 4;
        settingsTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F));
        settingsTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F));
        settingsTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        settingsTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
        settingsTableLayoutPanel.TabIndex = 0;
        resultCountLabel.Dock = DockStyle.Fill;
        resultCountLabel.Margin = new Padding(3, 0, 3, 0);
        resultCountLabel.Name = "resultCountLabel";
        resultCountLabel.Text = "0 個項目";
        resultCountLabel.TextAlign = ContentAlignment.MiddleLeft;
        assetPreviewViewport.Dock = DockStyle.Fill;
        assetPreviewViewport.Margin = new Padding(3, 2, 3, 2);
        assetPreviewViewport.Name = "assetPreviewViewport";
        assetPreviewViewport.ShowMaximizeButton = false;
        assetPreviewViewport.ShowScaleBar = false;
        assetPreviewViewport.TabIndex = 0;
        assetPreviewViewport.ViewKind = InteriorViewportKind.Perspective;
        assetToolTip.SetToolTip(assetPreviewViewport,
            "左鍵旋轉、中鍵移動目標、右鍵平移、滾輪縮放");
        framePreviewButton.Dock = DockStyle.Fill;
        framePreviewButton.Enabled = false;
        framePreviewButton.Margin = new Padding(3, 2, 3, 2);
        framePreviewButton.MinimumSize = new Size(0, 34);
        framePreviewButton.Name = "framePreviewButton";
        framePreviewButton.TabIndex = 1;
        framePreviewButton.Text = "自動置中／完整顯示";
        framePreviewButton.UseVisualStyleBackColor = true;
        framePreviewButton.Click += FramePreviewButton_Click;
        pbrPreviewButton.Dock = DockStyle.Fill;
        pbrPreviewButton.Enabled = false;
        pbrPreviewButton.Margin = new Padding(2);
        pbrPreviewButton.MinimumSize = new Size(0, 34);
        pbrPreviewButton.Name = "pbrPreviewButton";
        pbrPreviewButton.TabIndex = 2;
        pbrPreviewButton.Text = "PBR 預覽";
        pbrPreviewButton.UseVisualStyleBackColor = true;
        pbrPreviewButton.Click += PbrPreviewButton_Click;
        detailLabel.Dock = DockStyle.Fill;
        detailLabel.AutoEllipsis = true;
        detailLabel.Margin = new Padding(3, 1, 3, 1);
        detailLabel.Name = "detailLabel";
        detailLabel.Text = "選取項目以查看來源、授權與尺寸。";
        detailLabel.TextAlign = ContentAlignment.MiddleLeft;
        assetToolTip.SetToolTip(detailLabel, "選取項目以查看來源、授權與尺寸。");
        qualityLabel.Dock = DockStyle.Fill;
        qualityLabel.AutoEllipsis = true;
        qualityLabel.Margin = new Padding(3, 1, 3, 1);
        qualityLabel.Name = "qualityLabel";
        qualityLabel.Text = "品質：未選取";
        qualityLabel.TextAlign = ContentAlignment.MiddleLeft;
        assetToolTip.SetToolTip(qualityLabel, "品質：未選取");
        placementSettingsPropertyGrid.Dock = DockStyle.Fill;
        placementSettingsPropertyGrid.HelpVisible = false;
        placementSettingsPropertyGrid.Margin = new Padding(3, 2, 3, 2);
        placementSettingsPropertyGrid.Name = "placementSettingsPropertyGrid";
        placementSettingsPropertyGrid.PropertySort = PropertySort.Categorized;
        placementSettingsPropertyGrid.TabIndex = 3;
        placementSettingsPropertyGrid.ToolbarVisible = false;
        placementSettingsPropertyGrid.PropertyValueChanged += PlacementSettingsPropertyGrid_PropertyValueChanged;
        buttonTableLayoutPanel.ColumnCount = 3;
        buttonTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33333F));
        buttonTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33333F));
        buttonTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33334F));
        buttonTableLayoutPanel.Controls.Add(editAssetButton, 0, 0);
        buttonTableLayoutPanel.Controls.Add(deleteAssetButton, 1, 0);
        buttonTableLayoutPanel.Controls.Add(placeButton, 2, 0);
        buttonTableLayoutPanel.Dock = DockStyle.Fill;
        buttonTableLayoutPanel.Name = "buttonTableLayoutPanel";
        buttonTableLayoutPanel.RowCount = 1;
        buttonTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        buttonTableLayoutPanel.TabIndex = 5;
        editAssetButton.Dock = DockStyle.Fill;
        editAssetButton.Enabled = false;
        editAssetButton.Margin = new Padding(2, 3, 2, 2);
        editAssetButton.Name = "editAssetButton";
        editAssetButton.TabIndex = 4;
        editAssetButton.Text = "編輯模型";
        editAssetButton.UseVisualStyleBackColor = true;
        editAssetButton.Click += EditAssetButton_Click;
        deleteAssetButton.Dock = DockStyle.Fill;
        deleteAssetButton.Enabled = false;
        deleteAssetButton.Margin = new Padding(2, 3, 2, 2);
        deleteAssetButton.Name = "deleteAssetButton";
        deleteAssetButton.TabIndex = 5;
        deleteAssetButton.Text = "刪除模型";
        deleteAssetButton.UseVisualStyleBackColor = true;
        deleteAssetButton.Click += DeleteAssetButton_Click;
        placeButton.Dock = DockStyle.Fill;
        placeButton.Enabled = false;
        placeButton.Margin = new Padding(2, 3, 2, 2);
        placeButton.Name = "placeButton";
        placeButton.TabIndex = 0;
        placeButton.Text = "置放模型";
        placeButton.UseVisualStyleBackColor = true;
        placeButton.Click += PlaceButton_Click;
        Controls.Add(placementSplitContainer);
        Controls.Add(filterTableLayoutPanel);
        Name = "AssetCategoryControl";
        Size = new Size(300, 650);
        filterTableLayoutPanel.ResumeLayout(false);
        filterTableLayoutPanel.PerformLayout();
        placementSplitContainer.Panel1.ResumeLayout(false);
        placementSplitContainer.Panel2.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)placementSplitContainer).EndInit();
        placementSplitContainer.ResumeLayout(false);
        detailPanel.ResumeLayout(false);
        previewSettingsSplitContainer.Panel1.ResumeLayout(false);
        previewSettingsSplitContainer.Panel2.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)previewSettingsSplitContainer).EndInit();
        previewSettingsSplitContainer.ResumeLayout(false);
        detailTableLayoutPanel.ResumeLayout(false);
        settingsTableLayoutPanel.ResumeLayout(false);
        buttonTableLayoutPanel.ResumeLayout(false);
        previewHostTableLayoutPanel.ResumeLayout(false);
        previewButtonTableLayoutPanel.ResumeLayout(false);
        ResumeLayout(false);
    }
}
