#nullable enable

namespace Rv3dViewer.RVInteriorDesignPlugin;

partial class InteriorAssetPbrPreviewForm
{
    private System.ComponentModel.IContainer? components;
    private SplitContainer mainSplitContainer = null!;
    private InteriorPreviewViewportControl pbrViewport = null!;
    private TableLayoutPanel settingsTableLayoutPanel = null!;
    private Label modelNameLabel = null!;
    private TextBox diagnosticsTextBox = null!;
    private GroupBox lightingGroupBox = null!;
    private TableLayoutPanel lightingTableLayoutPanel = null!;
    private Label lightingLabel = null!;
    private TrackBar lightingTrackBar = null!;
    private Label lightingValueLabel = null!;
    private Label environmentLabel = null!;
    private TrackBar environmentTrackBar = null!;
    private Label environmentValueLabel = null!;
    private ComboBox backgroundComboBox = null!;
    private CheckBox showGridCheckBox = null!;
    private CheckBox showEnvironmentCheckBox = null!;
    private FlowLayoutPanel environmentButtonPanel = null!;
    private Button loadEnvironmentButton = null!;
    private Button clearEnvironmentButton = null!;
    private Label environmentFileLabel = null!;
    private TableLayoutPanel actionTableLayoutPanel = null!;
    private Button frameButton = null!;
    private Button closeButton = null!;
    private StatusStrip statusStrip = null!;
    private ToolStripStatusLabel statusLabel = null!;
    private OpenFileDialog environmentOpenFileDialog = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        mainSplitContainer = new SplitContainer();
        pbrViewport = new InteriorPreviewViewportControl();
        settingsTableLayoutPanel = new TableLayoutPanel();
        modelNameLabel = new Label();
        diagnosticsTextBox = new TextBox();
        lightingGroupBox = new GroupBox();
        lightingTableLayoutPanel = new TableLayoutPanel();
        lightingLabel = new Label();
        lightingTrackBar = new TrackBar();
        lightingValueLabel = new Label();
        environmentLabel = new Label();
        environmentTrackBar = new TrackBar();
        environmentValueLabel = new Label();
        backgroundComboBox = new ComboBox();
        showGridCheckBox = new CheckBox();
        showEnvironmentCheckBox = new CheckBox();
        environmentButtonPanel = new FlowLayoutPanel();
        loadEnvironmentButton = new Button();
        clearEnvironmentButton = new Button();
        environmentFileLabel = new Label();
        actionTableLayoutPanel = new TableLayoutPanel();
        frameButton = new Button();
        closeButton = new Button();
        statusStrip = new StatusStrip();
        statusLabel = new ToolStripStatusLabel();
        environmentOpenFileDialog = new OpenFileDialog();
        ((System.ComponentModel.ISupportInitialize)mainSplitContainer).BeginInit();
        mainSplitContainer.Panel1.SuspendLayout();
        mainSplitContainer.Panel2.SuspendLayout();
        mainSplitContainer.SuspendLayout();
        settingsTableLayoutPanel.SuspendLayout();
        lightingGroupBox.SuspendLayout();
        lightingTableLayoutPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)lightingTrackBar).BeginInit();
        ((System.ComponentModel.ISupportInitialize)environmentTrackBar).BeginInit();
        environmentButtonPanel.SuspendLayout();
        actionTableLayoutPanel.SuspendLayout();
        statusStrip.SuspendLayout();
        SuspendLayout();
        mainSplitContainer.Dock = DockStyle.Fill;
        mainSplitContainer.FixedPanel = FixedPanel.Panel2;
        mainSplitContainer.Name = "mainSplitContainer";
        mainSplitContainer.Panel1.Controls.Add(pbrViewport);
        mainSplitContainer.Panel1MinSize = 480;
        mainSplitContainer.Panel2.Controls.Add(settingsTableLayoutPanel);
        mainSplitContainer.Panel2MinSize = 300;
        mainSplitContainer.Size = new Size(1100, 696);
        mainSplitContainer.SplitterDistance = 790;
        mainSplitContainer.SplitterWidth = 6;
        mainSplitContainer.TabIndex = 0;
        pbrViewport.Dock = DockStyle.Fill;
        pbrViewport.Name = "pbrViewport";
        pbrViewport.TabIndex = 0;
        settingsTableLayoutPanel.ColumnCount = 1;
        settingsTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        settingsTableLayoutPanel.Controls.Add(modelNameLabel, 0, 0);
        settingsTableLayoutPanel.Controls.Add(diagnosticsTextBox, 0, 1);
        settingsTableLayoutPanel.Controls.Add(lightingGroupBox, 0, 2);
        settingsTableLayoutPanel.Controls.Add(actionTableLayoutPanel, 0, 3);
        settingsTableLayoutPanel.Dock = DockStyle.Fill;
        settingsTableLayoutPanel.Padding = new Padding(6);
        settingsTableLayoutPanel.RowCount = 4;
        settingsTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F));
        settingsTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 45F));
        settingsTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 55F));
        settingsTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
        modelNameLabel.Dock = DockStyle.Fill;
        modelNameLabel.Font = new Font(modelNameLabel.Font, FontStyle.Bold);
        modelNameLabel.Text = "模型";
        modelNameLabel.TextAlign = ContentAlignment.MiddleLeft;
        diagnosticsTextBox.Dock = DockStyle.Fill;
        diagnosticsTextBox.Multiline = true;
        diagnosticsTextBox.ReadOnly = true;
        diagnosticsTextBox.ScrollBars = ScrollBars.Both;
        diagnosticsTextBox.WordWrap = false;
        lightingGroupBox.Controls.Add(lightingTableLayoutPanel);
        lightingGroupBox.Dock = DockStyle.Fill;
        lightingGroupBox.Text = "PBR 環境與光源";
        lightingTableLayoutPanel.ColumnCount = 3;
        lightingTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 82F));
        lightingTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        lightingTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 48F));
        lightingTableLayoutPanel.Controls.Add(lightingLabel, 0, 0);
        lightingTableLayoutPanel.Controls.Add(lightingTrackBar, 1, 0);
        lightingTableLayoutPanel.Controls.Add(lightingValueLabel, 2, 0);
        lightingTableLayoutPanel.Controls.Add(environmentLabel, 0, 1);
        lightingTableLayoutPanel.Controls.Add(environmentTrackBar, 1, 1);
        lightingTableLayoutPanel.Controls.Add(environmentValueLabel, 2, 1);
        lightingTableLayoutPanel.Controls.Add(backgroundComboBox, 0, 2);
        lightingTableLayoutPanel.SetColumnSpan(backgroundComboBox, 3);
        lightingTableLayoutPanel.Controls.Add(showGridCheckBox, 0, 3);
        lightingTableLayoutPanel.SetColumnSpan(showGridCheckBox, 3);
        lightingTableLayoutPanel.Controls.Add(showEnvironmentCheckBox, 0, 4);
        lightingTableLayoutPanel.SetColumnSpan(showEnvironmentCheckBox, 3);
        lightingTableLayoutPanel.Controls.Add(environmentButtonPanel, 0, 5);
        lightingTableLayoutPanel.SetColumnSpan(environmentButtonPanel, 3);
        lightingTableLayoutPanel.Controls.Add(environmentFileLabel, 0, 6);
        lightingTableLayoutPanel.SetColumnSpan(environmentFileLabel, 3);
        lightingTableLayoutPanel.Dock = DockStyle.Fill;
        lightingTableLayoutPanel.RowCount = 7;
        lightingTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 46F));
        lightingTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 46F));
        lightingTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        lightingTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        lightingTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        lightingTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 38F));
        lightingTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        lightingLabel.Dock = DockStyle.Fill;
        lightingLabel.Text = "光源強度";
        lightingLabel.TextAlign = ContentAlignment.MiddleLeft;
        lightingTrackBar.Dock = DockStyle.Fill;
        lightingTrackBar.Maximum = 300;
        lightingTrackBar.Minimum = 10;
        lightingTrackBar.TickFrequency = 25;
        lightingTrackBar.Value = 100;
        lightingTrackBar.ValueChanged += LightingTrackBar_ValueChanged;
        lightingValueLabel.Dock = DockStyle.Fill;
        lightingValueLabel.Text = "1.00×";
        lightingValueLabel.TextAlign = ContentAlignment.MiddleCenter;
        environmentLabel.Dock = DockStyle.Fill;
        environmentLabel.Text = "環境強度";
        environmentLabel.TextAlign = ContentAlignment.MiddleLeft;
        environmentTrackBar.Dock = DockStyle.Fill;
        environmentTrackBar.Maximum = 200;
        environmentTrackBar.TickFrequency = 20;
        environmentTrackBar.Value = 20;
        environmentTrackBar.ValueChanged += EnvironmentTrackBar_ValueChanged;
        environmentValueLabel.Dock = DockStyle.Fill;
        environmentValueLabel.Text = "1.00";
        environmentValueLabel.TextAlign = ContentAlignment.MiddleCenter;
        backgroundComboBox.Dock = DockStyle.Fill;
        backgroundComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
        backgroundComboBox.Items.AddRange(new object[] { "深色背景", "淺色背景", "中性灰背景" });
        backgroundComboBox.SelectedIndexChanged += BackgroundControl_Changed;
        showGridCheckBox.AutoSize = true;
        showGridCheckBox.Checked = true;
        showGridCheckBox.Text = "顯示格點與座標軸";
        showGridCheckBox.CheckedChanged += BackgroundControl_Changed;
        showEnvironmentCheckBox.AutoSize = true;
        showEnvironmentCheckBox.Checked = true;
        showEnvironmentCheckBox.Text = "顯示 HDRI 背景";
        showEnvironmentCheckBox.CheckedChanged += BackgroundControl_Changed;
        environmentButtonPanel.Controls.Add(loadEnvironmentButton);
        environmentButtonPanel.Controls.Add(clearEnvironmentButton);
        environmentButtonPanel.Dock = DockStyle.Fill;
        environmentButtonPanel.FlowDirection = FlowDirection.LeftToRight;
        loadEnvironmentButton.Size = new Size(116, 30);
        loadEnvironmentButton.Text = "載入 HDRI";
        loadEnvironmentButton.UseVisualStyleBackColor = true;
        loadEnvironmentButton.Click += LoadEnvironmentButton_Click;
        clearEnvironmentButton.Size = new Size(116, 30);
        clearEnvironmentButton.Text = "清除 HDRI";
        clearEnvironmentButton.UseVisualStyleBackColor = true;
        clearEnvironmentButton.Click += ClearEnvironmentButton_Click;
        environmentFileLabel.AutoEllipsis = true;
        environmentFileLabel.Dock = DockStyle.Fill;
        environmentFileLabel.Text = "未載入 HDRI";
        actionTableLayoutPanel.ColumnCount = 2;
        actionTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        actionTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        actionTableLayoutPanel.Controls.Add(frameButton, 0, 0);
        actionTableLayoutPanel.Controls.Add(closeButton, 1, 0);
        actionTableLayoutPanel.Dock = DockStyle.Fill;
        frameButton.Dock = DockStyle.Fill;
        frameButton.Margin = new Padding(2, 4, 2, 2);
        frameButton.Text = "自動置中";
        frameButton.UseVisualStyleBackColor = true;
        frameButton.Click += FrameButton_Click;
        closeButton.Dock = DockStyle.Fill;
        closeButton.Margin = new Padding(2, 4, 2, 2);
        closeButton.Text = "關閉";
        closeButton.UseVisualStyleBackColor = true;
        closeButton.Click += CloseButton_Click;
        statusStrip.Items.AddRange(new ToolStripItem[] { statusLabel });
        statusStrip.Dock = DockStyle.Bottom;
        statusLabel.Spring = true;
        statusLabel.Text = "正在準備 PBR 預覽…";
        statusLabel.TextAlign = ContentAlignment.MiddleLeft;
        environmentOpenFileDialog.Filter = "Radiance HDR (*.hdr)|*.hdr|所有檔案 (*.*)|*.*";
        environmentOpenFileDialog.Title = "選取 PBR 預覽環境 HDRI";
        AcceptButton = closeButton;
        AutoScaleMode = AutoScaleMode.Font;
        ClientSize = new Size(1100, 720);
        Controls.Add(mainSplitContainer);
        Controls.Add(statusStrip);
        MinimumSize = new Size(820, 560);
        Name = "InteriorAssetPbrPreviewForm";
        StartPosition = FormStartPosition.CenterParent;
        Text = "模型 PBR 預覽";
        FormClosing += InteriorAssetPbrPreviewForm_FormClosing;
        Shown += InteriorAssetPbrPreviewForm_Shown;
        mainSplitContainer.Panel1.ResumeLayout(false);
        mainSplitContainer.Panel2.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)mainSplitContainer).EndInit();
        mainSplitContainer.ResumeLayout(false);
        settingsTableLayoutPanel.ResumeLayout(false);
        settingsTableLayoutPanel.PerformLayout();
        lightingGroupBox.ResumeLayout(false);
        lightingTableLayoutPanel.ResumeLayout(false);
        lightingTableLayoutPanel.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)lightingTrackBar).EndInit();
        ((System.ComponentModel.ISupportInitialize)environmentTrackBar).EndInit();
        environmentButtonPanel.ResumeLayout(false);
        actionTableLayoutPanel.ResumeLayout(false);
        statusStrip.ResumeLayout(false);
        statusStrip.PerformLayout();
        ResumeLayout(false);
        PerformLayout();
    }
}
