#nullable enable

namespace Rv3dViewer.RVInteriorDesignPlugin;

partial class PolyHavenAssetBrowserControl
{
    private System.ComponentModel.IContainer? components;
    private TableLayoutPanel browserTableLayoutPanel = null!;
    private TableLayoutPanel searchTableLayoutPanel = null!;
    private ComboBox providerComboBox = null!;
    private TextBox searchTextBox = null!;
    private ComboBox categoryComboBox = null!;
    private Button refreshButton = null!;
    private SplitContainer onlinePreviewSplitContainer = null!;
    private ListView onlineAssetsListView = null!;
    private ColumnHeader previewColumnHeader = null!;
    private ColumnHeader nameColumnHeader = null!;
    private ColumnHeader categoryColumnHeader = null!;
    private ColumnHeader polycountColumnHeader = null!;
    private ImageList onlineThumbnailImageList = null!;
    private Panel onlineDetailPanel = null!;
    private TableLayoutPanel onlineDetailTableLayoutPanel = null!;
    private PictureBox onlinePreviewPictureBox = null!;
    private Label onlineNameLabel = null!;
    private Label onlineInfoLabel = null!;
    private ComboBox resolutionComboBox = null!;
    private Button downloadButton = null!;
    private Label browserStatusLabel = null!;
    private LinkLabel attributionLinkLabel = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            PrepareForDispose();
            components?.Dispose();
        }
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        browserTableLayoutPanel = new TableLayoutPanel();
        searchTableLayoutPanel = new TableLayoutPanel();
        providerComboBox = new ComboBox();
        searchTextBox = new TextBox();
        categoryComboBox = new ComboBox();
        refreshButton = new Button();
        onlinePreviewSplitContainer = new SplitContainer();
        onlineAssetsListView = new ListView();
        previewColumnHeader = new ColumnHeader();
        nameColumnHeader = new ColumnHeader();
        categoryColumnHeader = new ColumnHeader();
        polycountColumnHeader = new ColumnHeader();
        onlineThumbnailImageList = new ImageList(components);
        onlineDetailPanel = new Panel();
        onlineDetailTableLayoutPanel = new TableLayoutPanel();
        onlinePreviewPictureBox = new PictureBox();
        onlineNameLabel = new Label();
        onlineInfoLabel = new Label();
        resolutionComboBox = new ComboBox();
        downloadButton = new Button();
        browserStatusLabel = new Label();
        attributionLinkLabel = new LinkLabel();
        browserTableLayoutPanel.SuspendLayout();
        searchTableLayoutPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)onlinePreviewSplitContainer).BeginInit();
        onlinePreviewSplitContainer.Panel1.SuspendLayout();
        onlinePreviewSplitContainer.Panel2.SuspendLayout();
        onlinePreviewSplitContainer.SuspendLayout();
        onlineDetailPanel.SuspendLayout();
        onlineDetailTableLayoutPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)onlinePreviewPictureBox).BeginInit();
        SuspendLayout();
        browserTableLayoutPanel.ColumnCount = 1;
        browserTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        browserTableLayoutPanel.Controls.Add(searchTableLayoutPanel, 0, 0);
        browserTableLayoutPanel.Controls.Add(onlinePreviewSplitContainer, 0, 1);
        browserTableLayoutPanel.Controls.Add(browserStatusLabel, 0, 2);
        browserTableLayoutPanel.Controls.Add(attributionLinkLabel, 0, 3);
        browserTableLayoutPanel.Dock = DockStyle.Fill;
        browserTableLayoutPanel.Name = "browserTableLayoutPanel";
        browserTableLayoutPanel.RowCount = 4;
        browserTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 98F));
        browserTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        browserTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        browserTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        searchTableLayoutPanel.ColumnCount = 2;
        searchTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 58F));
        searchTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 42F));
        searchTableLayoutPanel.Controls.Add(providerComboBox, 0, 0);
        searchTableLayoutPanel.Controls.Add(searchTextBox, 0, 1);
        searchTableLayoutPanel.Controls.Add(categoryComboBox, 1, 1);
        searchTableLayoutPanel.Controls.Add(refreshButton, 1, 2);
        searchTableLayoutPanel.Dock = DockStyle.Fill;
        searchTableLayoutPanel.Name = "searchTableLayoutPanel";
        searchTableLayoutPanel.RowCount = 3;
        searchTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        searchTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        searchTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        providerComboBox.Dock = DockStyle.Fill;
        providerComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
        providerComboBox.Items.AddRange(new object[] { "Poly Haven", "ambientCG" });
        providerComboBox.Name = "providerComboBox";
        providerComboBox.SelectedIndex = 0;
        searchTableLayoutPanel.SetColumnSpan(providerComboBox, 2);
        providerComboBox.SelectedIndexChanged += ProviderComboBox_SelectedIndexChanged;
        searchTextBox.Dock = DockStyle.Fill;
        searchTextBox.Name = "searchTextBox";
        searchTextBox.PlaceholderText = "搜尋 Poly Haven 模型";
        searchTextBox.TextChanged += SearchControl_Changed;
        categoryComboBox.Dock = DockStyle.Fill;
        categoryComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
        categoryComboBox.Name = "categoryComboBox";
        categoryComboBox.SelectedIndexChanged += SearchControl_Changed;
        refreshButton.Dock = DockStyle.Fill;
        refreshButton.Name = "refreshButton";
        refreshButton.Text = "重新載入";
        refreshButton.UseVisualStyleBackColor = true;
        refreshButton.Click += RefreshButton_Click;
        onlinePreviewSplitContainer.Dock = DockStyle.Fill;
        onlinePreviewSplitContainer.FixedPanel = FixedPanel.Panel2;
        onlinePreviewSplitContainer.Name = "onlinePreviewSplitContainer";
        onlinePreviewSplitContainer.Orientation = Orientation.Horizontal;
        onlinePreviewSplitContainer.Panel1.Controls.Add(onlineAssetsListView);
        onlinePreviewSplitContainer.Panel1MinSize = 100;
        onlinePreviewSplitContainer.Panel2.Controls.Add(onlineDetailPanel);
        onlinePreviewSplitContainer.Panel2MinSize = 180;
        onlinePreviewSplitContainer.Size = new Size(354, 494);
        onlinePreviewSplitContainer.SplitterDistance = 170;
        onlinePreviewSplitContainer.SplitterWidth = 6;
        onlinePreviewSplitContainer.TabIndex = 1;
        onlinePreviewSplitContainer.SplitterMoved += OnlinePreviewSplitContainer_SplitterMoved;
        onlineAssetsListView.Columns.AddRange(new[] { previewColumnHeader, nameColumnHeader,
            categoryColumnHeader, polycountColumnHeader });
        onlineAssetsListView.Dock = DockStyle.Fill;
        onlineAssetsListView.FullRowSelect = true;
        onlineAssetsListView.GridLines = true;
        onlineAssetsListView.HideSelection = false;
        onlineAssetsListView.MultiSelect = false;
        onlineAssetsListView.Name = "onlineAssetsListView";
        onlineAssetsListView.SmallImageList = onlineThumbnailImageList;
        onlineAssetsListView.UseCompatibleStateImageBehavior = false;
        onlineAssetsListView.View = View.Details;
        onlineAssetsListView.SelectedIndexChanged += OnlineAssetsListView_SelectedIndexChanged;
        previewColumnHeader.Text = "預覽";
        previewColumnHeader.Width = 70;
        nameColumnHeader.Text = "名稱";
        nameColumnHeader.Width = 140;
        categoryColumnHeader.Text = "分類";
        categoryColumnHeader.Width = 100;
        polycountColumnHeader.Text = "面數";
        polycountColumnHeader.Width = 90;
        onlineThumbnailImageList.ColorDepth = ColorDepth.Depth32Bit;
        onlineThumbnailImageList.ImageSize = new Size(64, 48);
        onlineThumbnailImageList.TransparentColor = Color.Transparent;
        onlineDetailPanel.Controls.Add(onlineDetailTableLayoutPanel);
        onlineDetailPanel.Dock = DockStyle.Fill;
        onlineDetailPanel.Name = "onlineDetailPanel";
        onlineDetailTableLayoutPanel.ColumnCount = 2;
        onlineDetailTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 48F));
        onlineDetailTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 52F));
        onlineDetailTableLayoutPanel.Controls.Add(onlinePreviewPictureBox, 0, 0);
        onlineDetailTableLayoutPanel.Controls.Add(onlineNameLabel, 1, 0);
        onlineDetailTableLayoutPanel.Controls.Add(onlineInfoLabel, 1, 1);
        onlineDetailTableLayoutPanel.Controls.Add(resolutionComboBox, 1, 2);
        onlineDetailTableLayoutPanel.Controls.Add(downloadButton, 1, 3);
        onlineDetailTableLayoutPanel.Dock = DockStyle.Fill;
        onlineDetailTableLayoutPanel.Name = "onlineDetailTableLayoutPanel";
        onlineDetailTableLayoutPanel.RowCount = 4;
        onlineDetailTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 15F));
        onlineDetailTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 43F));
        onlineDetailTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 18F));
        onlineDetailTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 24F));
        onlinePreviewPictureBox.BackColor = Color.FromArgb(29, 34, 40);
        onlinePreviewPictureBox.BorderStyle = BorderStyle.FixedSingle;
        onlinePreviewPictureBox.Dock = DockStyle.Fill;
        onlinePreviewPictureBox.Margin = new Padding(4);
        onlinePreviewPictureBox.Name = "onlinePreviewPictureBox";
        onlinePreviewPictureBox.SizeMode = PictureBoxSizeMode.Zoom;
        onlineDetailTableLayoutPanel.SetRowSpan(onlinePreviewPictureBox, 4);
        onlineNameLabel.AutoEllipsis = true;
        onlineNameLabel.Dock = DockStyle.Fill;
        onlineNameLabel.Font = new Font(Font, FontStyle.Bold);
        onlineNameLabel.Margin = new Padding(4, 4, 4, 0);
        onlineNameLabel.Name = "onlineNameLabel";
        onlineNameLabel.Text = "選取線上模型";
        onlineNameLabel.TextAlign = ContentAlignment.MiddleLeft;
        onlineInfoLabel.AutoEllipsis = true;
        onlineInfoLabel.Dock = DockStyle.Fill;
        onlineInfoLabel.Margin = new Padding(4, 0, 4, 2);
        onlineInfoLabel.Name = "onlineInfoLabel";
        onlineInfoLabel.Text = "Poly Haven 模型為 CC0，可商用。";
        resolutionComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
        resolutionComboBox.Dock = DockStyle.Fill;
        resolutionComboBox.Enabled = false;
        resolutionComboBox.Margin = new Padding(4, 3, 4, 3);
        resolutionComboBox.MinimumSize = new Size(100, 0);
        resolutionComboBox.Name = "resolutionComboBox";
        resolutionComboBox.SelectedIndexChanged += ResolutionComboBox_SelectedIndexChanged;
        downloadButton.Dock = DockStyle.Fill;
        downloadButton.Enabled = false;
        downloadButton.Margin = new Padding(4, 3, 4, 4);
        downloadButton.MinimumSize = new Size(150, 31);
        downloadButton.Name = "downloadButton";
        downloadButton.Text = "下載並加入本機模型庫";
        downloadButton.UseVisualStyleBackColor = true;
        downloadButton.Click += DownloadButton_Click;
        browserStatusLabel.AutoEllipsis = true;
        browserStatusLabel.Dock = DockStyle.Fill;
        browserStatusLabel.Name = "browserStatusLabel";
        browserStatusLabel.Padding = new Padding(4, 4, 4, 0);
        browserStatusLabel.Text = "開啟線上模型頁面後將載入清單。";
        attributionLinkLabel.Dock = DockStyle.Fill;
        attributionLinkLabel.LinkArea = new LinkArea(11, 10);
        attributionLinkLabel.Name = "attributionLinkLabel";
        attributionLinkLabel.Padding = new Padding(4, 4, 4, 0);
        attributionLinkLabel.Text = "CC0 資產來源：Poly Haven";
        attributionLinkLabel.LinkClicked += AttributionLinkLabel_LinkClicked;
        Controls.Add(browserTableLayoutPanel);
        Name = "PolyHavenAssetBrowserControl";
        Size = new Size(360, 620);
        browserTableLayoutPanel.ResumeLayout(false);
        searchTableLayoutPanel.ResumeLayout(false);
        searchTableLayoutPanel.PerformLayout();
        onlinePreviewSplitContainer.Panel1.ResumeLayout(false);
        onlinePreviewSplitContainer.Panel2.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)onlinePreviewSplitContainer).EndInit();
        onlinePreviewSplitContainer.ResumeLayout(false);
        onlineDetailPanel.ResumeLayout(false);
        onlineDetailTableLayoutPanel.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)onlinePreviewPictureBox).EndInit();
        ResumeLayout(false);
    }
}
