#nullable enable

namespace Rv3dViewer.Plugin.WinForms;

partial class RichColorPickerForm
{
    private System.ComponentModel.IContainer? components;
    private TableLayoutPanel mainLayoutPanel = null!;
    private TableLayoutPanel visualPickerLayoutPanel = null!;
    private ColorWheelControl colorWheel = null!;
    private ColorComponentSlider valueSlider = null!;
    private ColorComponentSlider alphaSlider = null!;
    private Panel previewPanel = null!;
    private Label hexLabel = null!;
    private TextBox hexTextBox = null!;
    private Label alphaLabel = null!;
    private NumericUpDown alphaNumericUpDown = null!;
    private Label redLabel = null!;
    private NumericUpDown redNumericUpDown = null!;
    private Label greenLabel = null!;
    private NumericUpDown greenNumericUpDown = null!;
    private Label blueLabel = null!;
    private NumericUpDown blueNumericUpDown = null!;
    private Label hueLabel = null!;
    private NumericUpDown hueNumericUpDown = null!;
    private Label saturationLabel = null!;
    private NumericUpDown saturationNumericUpDown = null!;
    private Label valueLabel = null!;
    private NumericUpDown valueNumericUpDown = null!;
    private FlowLayoutPanel buttonsPanel = null!;
    private Button okButton = null!;
    private Button applyButton = null!;
    private Button cancelButton = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        mainLayoutPanel = new TableLayoutPanel();
        visualPickerLayoutPanel = new TableLayoutPanel();
        colorWheel = new ColorWheelControl();
        valueSlider = new ColorComponentSlider();
        alphaSlider = new ColorComponentSlider();
        previewPanel = new Panel();
        hexLabel = new Label();
        hexTextBox = new TextBox();
        alphaLabel = new Label();
        alphaNumericUpDown = new NumericUpDown();
        redLabel = new Label();
        redNumericUpDown = new NumericUpDown();
        greenLabel = new Label();
        greenNumericUpDown = new NumericUpDown();
        blueLabel = new Label();
        blueNumericUpDown = new NumericUpDown();
        hueLabel = new Label();
        hueNumericUpDown = new NumericUpDown();
        saturationLabel = new Label();
        saturationNumericUpDown = new NumericUpDown();
        valueLabel = new Label();
        valueNumericUpDown = new NumericUpDown();
        buttonsPanel = new FlowLayoutPanel();
        okButton = new Button();
        applyButton = new Button();
        cancelButton = new Button();
        mainLayoutPanel.SuspendLayout();
        visualPickerLayoutPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)alphaNumericUpDown).BeginInit();
        ((System.ComponentModel.ISupportInitialize)redNumericUpDown).BeginInit();
        ((System.ComponentModel.ISupportInitialize)greenNumericUpDown).BeginInit();
        ((System.ComponentModel.ISupportInitialize)blueNumericUpDown).BeginInit();
        ((System.ComponentModel.ISupportInitialize)hueNumericUpDown).BeginInit();
        ((System.ComponentModel.ISupportInitialize)saturationNumericUpDown).BeginInit();
        ((System.ComponentModel.ISupportInitialize)valueNumericUpDown).BeginInit();
        buttonsPanel.SuspendLayout();
        SuspendLayout();
        mainLayoutPanel.ColumnCount = 4;
        mainLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
        mainLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        mainLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
        mainLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        mainLayoutPanel.Controls.Add(visualPickerLayoutPanel, 0, 0);
        mainLayoutPanel.Controls.Add(alphaSlider, 0, 1);
        mainLayoutPanel.Controls.Add(hexLabel, 0, 2);
        mainLayoutPanel.Controls.Add(hexTextBox, 1, 2);
        mainLayoutPanel.Controls.Add(alphaLabel, 2, 2);
        mainLayoutPanel.Controls.Add(alphaNumericUpDown, 3, 2);
        mainLayoutPanel.Controls.Add(redLabel, 0, 3);
        mainLayoutPanel.Controls.Add(redNumericUpDown, 1, 3);
        mainLayoutPanel.Controls.Add(greenLabel, 2, 3);
        mainLayoutPanel.Controls.Add(greenNumericUpDown, 3, 3);
        mainLayoutPanel.Controls.Add(blueLabel, 0, 4);
        mainLayoutPanel.Controls.Add(blueNumericUpDown, 1, 4);
        mainLayoutPanel.Controls.Add(hueLabel, 2, 4);
        mainLayoutPanel.Controls.Add(hueNumericUpDown, 3, 4);
        mainLayoutPanel.Controls.Add(saturationLabel, 0, 5);
        mainLayoutPanel.Controls.Add(saturationNumericUpDown, 1, 5);
        mainLayoutPanel.Controls.Add(valueLabel, 2, 5);
        mainLayoutPanel.Controls.Add(valueNumericUpDown, 3, 5);
        mainLayoutPanel.Controls.Add(buttonsPanel, 0, 6);
        mainLayoutPanel.Dock = DockStyle.Fill;
        mainLayoutPanel.Location = new Point(12, 12);
        mainLayoutPanel.Name = "mainLayoutPanel";
        mainLayoutPanel.RowCount = 7;
        mainLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 326F));
        mainLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        mainLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mainLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mainLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mainLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mainLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 58F));
        mainLayoutPanel.Size = new Size(516, 636);
        mainLayoutPanel.TabIndex = 0;
        mainLayoutPanel.SetColumnSpan(visualPickerLayoutPanel, 4);
        visualPickerLayoutPanel.ColumnCount = 2;
        visualPickerLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 84F));
        visualPickerLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 16F));
        visualPickerLayoutPanel.Controls.Add(colorWheel, 0, 0);
        visualPickerLayoutPanel.Controls.Add(valueSlider, 1, 0);
        visualPickerLayoutPanel.Controls.Add(previewPanel, 1, 1);
        visualPickerLayoutPanel.Dock = DockStyle.Fill;
        visualPickerLayoutPanel.Name = "visualPickerLayoutPanel";
        visualPickerLayoutPanel.RowCount = 2;
        visualPickerLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 82F));
        visualPickerLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 18F));
        visualPickerLayoutPanel.SetRowSpan(colorWheel, 2);
        colorWheel.Dock = DockStyle.Fill;
        colorWheel.Name = "colorWheel";
        colorWheel.SelectionChanged += ColorWheel_SelectionChanged;
        colorWheel.InteractionCompleted += ColorPicker_InteractionCompleted;
        valueSlider.Component = ColorSliderComponent.Value;
        valueSlider.Dock = DockStyle.Fill;
        valueSlider.Name = "valueSlider";
        valueSlider.Orientation = Orientation.Vertical;
        valueSlider.ComponentChanged += ValueSlider_ComponentChanged;
        valueSlider.InteractionCompleted += ColorPicker_InteractionCompleted;
        mainLayoutPanel.SetColumnSpan(alphaSlider, 4);
        alphaSlider.Component = ColorSliderComponent.Alpha;
        alphaSlider.Dock = DockStyle.Fill;
        alphaSlider.Name = "alphaSlider";
        alphaSlider.Orientation = Orientation.Horizontal;
        alphaSlider.ComponentChanged += AlphaSlider_ComponentChanged;
        alphaSlider.InteractionCompleted += ColorPicker_InteractionCompleted;
        previewPanel.BorderStyle = BorderStyle.FixedSingle;
        previewPanel.Dock = DockStyle.Fill;
        previewPanel.Name = "previewPanel";
        previewPanel.TabIndex = 0;
        hexLabel.Anchor = AnchorStyles.Left;
        hexLabel.AutoSize = true;
        hexLabel.Text = "HEX";
        hexTextBox.Dock = DockStyle.Fill;
        hexTextBox.Name = "hexTextBox";
        hexTextBox.Validated += HexTextBox_Validated;
        ConfigureLabel(alphaLabel, "Alpha");
        ConfigureLabel(redLabel, "Red");
        ConfigureLabel(greenLabel, "Green");
        ConfigureLabel(blueLabel, "Blue");
        ConfigureLabel(hueLabel, "Hue");
        ConfigureLabel(saturationLabel, "Saturation %");
        ConfigureLabel(valueLabel, "Value %");
        ConfigureByteNumeric(alphaNumericUpDown);
        ConfigureByteNumeric(redNumericUpDown);
        ConfigureByteNumeric(greenNumericUpDown);
        ConfigureByteNumeric(blueNumericUpDown);
        hueNumericUpDown.Dock = DockStyle.Fill;
        hueNumericUpDown.Maximum = 360;
        hueNumericUpDown.ValueChanged += Hsv_ValueChanged;
        saturationNumericUpDown.Dock = DockStyle.Fill;
        saturationNumericUpDown.ValueChanged += Hsv_ValueChanged;
        valueNumericUpDown.Dock = DockStyle.Fill;
        valueNumericUpDown.ValueChanged += Hsv_ValueChanged;
        saturationNumericUpDown.Maximum = 100;
        valueNumericUpDown.Maximum = 100;
        alphaNumericUpDown.ValueChanged += Rgba_ValueChanged;
        redNumericUpDown.ValueChanged += Rgba_ValueChanged;
        greenNumericUpDown.ValueChanged += Rgba_ValueChanged;
        blueNumericUpDown.ValueChanged += Rgba_ValueChanged;
        mainLayoutPanel.SetColumnSpan(buttonsPanel, 4);
        buttonsPanel.Controls.Add(cancelButton);
        buttonsPanel.Controls.Add(okButton);
        buttonsPanel.Controls.Add(applyButton);
        buttonsPanel.Dock = DockStyle.Fill;
        buttonsPanel.FlowDirection = FlowDirection.RightToLeft;
        buttonsPanel.Name = "buttonsPanel";
        buttonsPanel.Padding = new Padding(0, 8, 0, 0);
        buttonsPanel.WrapContents = false;
        cancelButton.DialogResult = DialogResult.Cancel;
        cancelButton.Margin = new Padding(6, 3, 0, 3);
        cancelButton.Name = "cancelButton";
        cancelButton.Size = new Size(88, 32);
        cancelButton.Text = "取消";
        cancelButton.UseVisualStyleBackColor = true;
        okButton.AutoSize = true;
        okButton.Name = "okButton";
        okButton.Size = new Size(116, 32);
        okButton.Text = "確定並套用";
        okButton.UseVisualStyleBackColor = true;
        okButton.Click += OkButton_Click;
        applyButton.AutoSize = true;
        applyButton.Name = "applyButton";
        applyButton.Size = new Size(88, 32);
        applyButton.Text = "套用";
        applyButton.UseVisualStyleBackColor = true;
        applyButton.Click += ApplyButton_Click;
        AcceptButton = okButton;
        AutoScaleMode = AutoScaleMode.None;
        CancelButton = cancelButton;
        ClientSize = new Size(540, 660);
        Controls.Add(mainLayoutPanel);
        FormBorderStyle = FormBorderStyle.FixedDialog;
        MaximizeBox = false;
        MinimizeBox = false;
        MinimumSize = new Size(556, 699);
        Name = "RichColorPickerForm";
        Padding = new Padding(12);
        ShowInTaskbar = false;
        StartPosition = FormStartPosition.CenterParent;
        Text = "選擇顏色";
        mainLayoutPanel.ResumeLayout(false);
        mainLayoutPanel.PerformLayout();
        visualPickerLayoutPanel.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)alphaNumericUpDown).EndInit();
        ((System.ComponentModel.ISupportInitialize)redNumericUpDown).EndInit();
        ((System.ComponentModel.ISupportInitialize)greenNumericUpDown).EndInit();
        ((System.ComponentModel.ISupportInitialize)blueNumericUpDown).EndInit();
        ((System.ComponentModel.ISupportInitialize)hueNumericUpDown).EndInit();
        ((System.ComponentModel.ISupportInitialize)saturationNumericUpDown).EndInit();
        ((System.ComponentModel.ISupportInitialize)valueNumericUpDown).EndInit();
        buttonsPanel.ResumeLayout(false);
        ResumeLayout(false);
    }

    private static void ConfigureLabel(Label label, string text)
    {
        label.Anchor = AnchorStyles.Left;
        label.AutoSize = true;
        label.Margin = new Padding(3, 6, 8, 6);
        label.Text = text;
    }

    private static void ConfigureByteNumeric(NumericUpDown control)
    {
        control.Dock = DockStyle.Fill;
        control.Maximum = 255;
    }
}
